### ISSUE TITLE
A001 System, CPU, RAM, disks, virtualization - collect data

### ISSUE THREAD

**Issue by ane4ka** [postgres-ai/postgres-health-check#6]
for multiple nodes in a single postgres replica set

**Comment by NikolayS** [comment]
❗️ see also https://github.com/postgres-ai/nancy/blob/master/nancy_run.sh#L800

System: 
- `uname -a`
- `hostnamectl status` (see https://serverfault.com/questions/595471/how-to-find-out-the-virtualization-type-of-an-linux-vps)

RAM: `cat /proc/meminfo` (with attention to: `MemTotal`, `Buffers`, `Cached`, `SwapTotal`, `HugePages_Total`)

Disks: `df -T`, with attention to the partition where $PGDATA is located -- use `df -T /path/to/PGDATA` (Ubuntu example: `df -T df -T /var/lib/postgresql/9.6/main/`, CentOS: `df -T df -T /var/lib/pgsql/9.6/data`)
