### ISSUE TITLE
A000 Json structure for mulitple hosts report

### ISSUE THREAD

**Issue by ane4ka** [postgres-ai/postgres-health-check#73]

**Comment by dmius** [comment]
Текущая структура 
```
{
  "checkId": "A003",
  "hosts": [
    "localhost"
  ],
  "dependencies": {
    "null": "null"
  },
  "result": {
    "localhost": []}
}
```
Где значение в массиве hosts является индексом в объекте result.

А нам для каждого хоста надо хранить роль, хост и данные и при этом простую адресацию.
Самый простой вариант
```
"hosts": {
    {
        name: "db1" 
         role: master, // всегда должен быть первым
        domain: db1.server.com
     },
    {
         name: "db2" 
         role: replica, // всегда должен быть первым
         domain: db1.server.com
    }
  },

  result:{
    "db1": {
       data
     }
  }
```
При этом адресация к данным сохраняется такая же,  а вот строка индекса берется из поля name в блоке описания host.

name := hosts[0].name  -  имя мастер сервера или может id 
result[name].* обращение к данным для хоста

@Nastradamus что думаешь?

**Comment by dmius** [comment]
А нет ли разницы где будет храниться шаблон структуры, может для начала со структурой определимся и я смогу уже парсингом структуры заняться, а  как это генериться будет это пока мне не важно.

**Comment by Nastradamus** [comment]
Ну для меня разница точно есть: менять в одном файле что-то если изменился маппинг "master - alias", или во всех десятках файлов сразу. Я сейчас как раз буду делать поддержку нескольких хостов и для меня это критично.

**Comment by dmius** [comment]
Ну наверно важнее определиться каков будет интерфейс между нами (твоий программой и моей), а как мы это будет реализовывать каждый у себя то не много не о том вопрос... или я чего то не понимаю

**Comment by Nastradamus** [comment]
В данный момент, я генерю json'ы и изменяю уже созданные. Если мы сделаем так как ты говоришь - это усложнит мне задачу непредсказуемым образом. Мало того, сломает гибкость.

**Comment by Nastradamus** [comment]
@dmius давай набросаем просто файлик как мы вчера все вместе договорились и закроем эту задачу.

**Comment by dmius** [comment]
Смотри мой первый пост.

**Comment by dmius** [comment]
> В данный момент, я генерю json'ы и изменяю уже созданные. Если мы сделаем так как ты говоришь - это усложнит мне задачу непредсказуемым образом. Мало того, сломает гибкость.

**Comment by Nastradamus** [comment]
См название таска.

**Comment by Nastradamus** [comment]
We decided to keep these json parts in every check.
But I will implement the following structure in `./check`:

```
{
  "hosts": {
    "hostname": {
      "role": null,
      "alias": null
    }
  },
  "last_check": {
    "id": null,
    "timestamp": null
  }
}
```
