### ISSUE TITLE
A006 Config diff - collect data

### ISSUE THREAD

**Issue by ane4ka** [postgres-ai/postgres-health-check#9]

**Comment by NikolayS** [comment]
Idea:

1) collect data for each node:

a) `select * from pg_config`
b) `select name, setting, unit, category from pg_settings`

Save two files for each node – one for `pg_config`, one for `pg_settings`.

2) If `diff`, find differences between the master node and each of replicas.

**Comment by dmius** [comment]
Насколько я понял @Nastradamus реализуется так что бы для каждого хоста(мастер, реплики) будет делаться свой вызов проверки, а потом он сам собирает это все в один json файл. Тогда получается что в скрипте отдельной проверки ничего не известно о других хостах. Получается что можно только собирать данные, а сравнение делать потом например в плагине.

**Comment by Nastradamus** [comment]
@NikolayS 

There can be a several config diffs: 

1) between master and standby's
2) between loaded into PostgreSQL memory and in the `postgresql.conf`

Which one did you mean?

**Comment by dmius** [comment]
Between two same configs from diffrerent domains.

**Comment by dmius** [comment]
Here https://github.com/postgres-ai/postgres-health-check/pull/80 collect data
